export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE";
export const ACTION_START = "ACTION_START";

export const ASSIGNMENT_ACTION_START = "ASSIGNMENT_ACTION_START";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";
export const GET_ASSIGNMENT_SUCCESS = "GET_ASSIGNMENT_SUCCESS";
export const ASSIGNMENT_ACTION_FAILED = "ASSIGNMENT_ACTION_FAILED";
export const UPDATE_ASSIGNMENT_SUCCESS = "UPDATE_ASSIGNMENT_SUCCESS";
export const DELETE_ASSIGNMENT_SUCCESS = "DELETE_ASSIGNMENT_SUCCESS";
export const CREATE_ASSIGNMENT_SUBMISSION_SUCCESS = "CREATE_ASSIGNMENT_SUBMISSION_SUCCESS";
export const GET_ASSIGNMENT_SUBMISSION_SUCCESS = "GET_ASSIGNMENT_SUBMISSION_SUCCESS";

export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_START = 'GET_MEMBERS_START';
export const GET_MEMBERS_FAIL = 'GET_MEMBERS_FAIL';

export const CREATE_COURSE_START = "CREATE_COURSE_START";
export const CREATE_COURSE_FAILURE = "CREATE_COURSE_FAILURE";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";